### ISSUE TITLE
Chrome/Edge v117 regression

### ISSUE THREAD

**Issue by legobeat** [MetaMask/phishing-warning#119]
For some reason, the Playwright CI jobs are now failing on `main`.

- Last good run on `main`: 7ebd4c1018190422b209e26c8ff584f2af16ccb3
- First commit on `main` with this issue: 678ab239e4f669a3f7d244cbaa4ade1580f8597e (#105)

However, CI was failing with the same error prior to the merge of #105 in parallel open PRs at the time: d41fd0201142fe75261b5bb37f033bfae44b36ea

So it seems likely this is actually a browser regression. Browser versions are fetched dynamically.

- Failing Chrome version: `117.0.5938.132`
- Passing Chrome version: `116.0.5845.140`
- Failing Edge version: `117.0.2045.40`
- Passing Edge version: `116.0.1938.62`

**Comment by brad-decker** [comment]
Edge failing tests are due to lockdown:

```
[
  'Lockdown failed: TypeError: At intrinsics.Object.groupBy expected boolean not function\n' +
    '  at isAllowedPropertyValue (http://localhost:8080/lockdown-install.js:1:53384)\n' +
    '  at isAllowedProperty (http://localhost:8080/lockdown-install.js:1:53807)\n' +
    '  at visitProperties (http://localhost:8080/lockdown-install.js:1:55095)\n' +
    '  at isAllowedPropertyValue (http://localhost:8080/lockdown-install.js:1:53041)\n' +
    '  at isAllowedProperty (http://localhost:8080/lockdown-install.js:1:53807)\n' +
    '  at visitProperties (http://localhost:8080/lockdown-install.js:1:55095)\n' +
    '  at http://localhost:8080/lockdown-install.js:1:55523\n' +
    '  at repairIntrinsics (http://localhost:8080/lockdown-install.js:1:144597)\n' +
    '  at http://localhost:8080/lockdown-install.js:1:145462\n' +
    '  at http://localhost:8080/lockdown-run.js:6:3',
  'Protecting intrinsics failed: ReferenceError: harden is not defined\n' +
    '  at http://localhost:8080/lockdown-more.js:67:11\n' +
    '  at Set.forEach (<anonymous>)\n' +
    '  at protectIntrinsics (http://localhost:8080/lockdown-more.js:43:22)\n' +
    '  at http://localhost:8080/lockdown-more.js:85:5',
  "Error: Missing 'hostname' query parameter\n" +
    '  at HTMLDocument.<anonymous> (http://localhost:8080/bundle.js:17:87510)'
]
```

Only one error should be in that array but there are two more due to lockdown

**Comment by brad-decker** [comment]
Same for chrome.
